export { default as CategoryHighlight } from './CategoryHighlight'
export { default as Fg } from './Fg';
export { default as Footer } from './Footer';
export { default as Hero } from './Hero';
export { default as MenuBar } from './MenuBar';
export { default as MostWanted } from './MostWanted';
export { default as NavBar } from './NavBar';
export { default as NewArrival } from './NewArrival';
export { default as SaleBar } from './SaleBar';
export { default as WhyUs } from './WhyUs';
export { default as Subscribe } from './Subscribe';
export { default as ImgSlider } from './ImgSlider';
export { default as ProductSlider } from './ProductSlider';
export { default as BackToHome } from './BackToHome';
export { default as Counter } from './Counter';
export { default as Product } from './Product';